nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:4200']  # Frontend Angular
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']  # Méthodes HTTP autorisées
        allow_headers: ['Content-Type', 'Authorization']  # En-têtes autorisés
        expose_headers: []  # En-têtes exposés au frontend
        max_age: 3600  # Durée de cache des pré-vols
        allow_credentials: true  # Permettre l'envoi de cookies ou d'en-têtes d'authentification
    paths:
        '^/api/':  # Préfixe des routes CORS (adapter si nécessaire)
            allow_origin: ['http://localhost:4200']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
